### PR TITLE
Update config.example.yml

### PR DESCRIPTION
**Pull request by androkh225**

### CODE REVIEW

**Comment by vhladiienko** [comment]
@androkh225 you shouldn't be putting your private keys in a public github repository. Needless to say, request to merge those into an open source project.

**Comment by Fl0p** [comment]
Tnx @androkh225

**Comment by Fl0p** [comment]
@androkh225 looks like your openai_api_key already restricted by Usage limits

**Comment by vhladiienko** [comment]
@Fl0p please, educate yourself about what a personal API key is before posting such things. They are meant for personal use for a reason. Of course leaked key in this PR is rotated. I mean, really? 

Screenshot_2023-06-16-00-32-16-767_com brave browser-edit

**Comment by karfly** [comment]
Good news is that OpenAI actively searches for leaked api keys and revokes them immediately.

**Pull request closed without merging**
