### PR TITLE
Added GPT Vision Support to Telegram Bot

### PR DESCRIPTION
**Pull request by ArtemStepanov**
Reference issue #390

This PR introduces the integration of GPT Vision into existing Telegram bot. With this update, the bot is now capable of describing images based on user inputs, leveraging the power of OpenAI's GPT Vision model.

### Changes include:

- Added new model.
- Integrated GPT Vision API calls within the bot's message handling logic.

### Usage:

- Send a plain and compressed photo to the chat, don't forget to put a proper caption to it.
- Wait for the response.
- Profit!

Please review and provide any feedback.

### CODE REVIEW

**Comment by adrianlzt** [comment]
I was testing this branch but I'm unable to make it work.
It returns the message"
```
Something went wrong during completion. Reason: local variable 'n_input_tokens' referenced before assignment
```.

Removing the exception capture:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1184, in process_update
    await coroutine
  File "/usr/local/lib/python3.8/site-packages/telegram/ext/_basehandler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/code/bot/handlers.py", line 53, in wrapper
    return await func(update, context, *args, **kwargs)
  File "/code/bot/handlers.py", line 62, in wrapper
    return await func(update, context, *args, **kwargs)
  File "/code/bot/handlers.py", line 596, in message_handle
    await task
  File "/code/bot/handlers.py", line 53, in wrapper
    return await func(update, context, *args, **kwargs)
  File "/code/bot/handlers.py", line 62, in wrapper
    return await func(update, context, *args, **kwargs)
  File "/code/bot/handlers.py", line 171, in _message_handle_fn
    async for gen_item in gen:
  File "/code/bot/openai_utils.py", line 270, in send_message_stream
    n_input_tokens,
UnboundLocalError: local variable 'n_input_tokens' referenced before assignment
```

Any idea what it could be?

I have taken a look at your changes, but I have no idea what could be producing that error.

**Comment by hvanmegen** [comment]
Do you want to start a fork of this bot that we can maintain? I don't like how unresponsive the original author is.

**Comment by adrianlzt** [comment]
Would be nice, but I do not have much spare time. Sorry

**Comment by ArtemStepanov** [comment]
I'm good with our own fork of it. But not sure how else can we improve the bot :)

**Comment by KenKout** [comment]
Something went wrong during completion. Reason: Unknown model: gpt-4-vision-preview
I don't think it's working

**Comment by ArtemStepanov** [comment]
> Something went wrong during completion. Reason: Unknown model: gpt-4-vision-preview
> 
> I don't think it's working

Thank you for your message.

Can you please clarify how did you set up your environment?

**Comment by KenKout** [comment]
I have clone this branch
https://github.com/ArtemStepanov/gpt4_vision_telegram_bot/tree/feat/gpt-vision
And I have setup by running docker-compose as usual, but it’s not working.
When I try to add gpt-4-vision-preview in array that cause this error, it
returns new error message:
Something went wrong during completion. Reason: expected string or buffer

**Pull request closed without merging**
