### PR TITLE
update readme to include bot commands and raspberry pi setup

### PR DESCRIPTION
**Pull request by preethaml7**
Firstly, thank you for your awesome work! 🙌  

I had to search online for instructions on setting up bot commands during the setup process, so I believe it would be beneficial to include this in the documentation. Additionally, I tested the project on raspberry pi arm64 and found that it works with just a small change to the mongo image used. If you feel this would be helpful to other users, please consider accepting this merge request. Thank you!

### CODE REVIEW

**Comment by gordinmitya** [comment]
@preethaml7 this readme section was recently deleted because now bot do commands setup automatically via api call https://github.com/karfly/chatgpt_telegram_bot/pull/127

**Comment by preethaml7** [comment]
@gordinmitya I set this up yesterday on a raspberry pi and the commands were not set up automatically for me. I had to manually add them.

**Comment by preethaml7** [comment]
@gordinmitya I pulled in the changes today, set this up as new and you're right! with the latest changes bot commands are being set up automatically.

**Comment by preethaml7** [comment]
I have updated the read me to just have raspberry pi setup instructions! which is just a change in the mongo image to make this work.

**Pull request closed without merging**
