### PR TITLE
Solution for Error "That model is currently overloaded with other requests"

### PR DESCRIPTION
**Pull request by bigbabybubble**

### CODE REVIEW

**Comment by soyelmismo** [comment]
It needs a max number of retries

**Comment by bigbabybubble** [comment]
> It needs a max number of retries

The task is that in any case the user will receive an answer, but not an error.
It is not a problem to add counter, but according to my practice, the number of retries did not exceed 10, in order to achieve a response in the condition of overloaded OpenAI servers.

**Comment by bigbabybubble** [comment]
```
while answer is None:
            retry = True
            attempt = 0
            if attempt < 10:
                while retry:
                    try:
                    ...
                    except Exception as e:
                        if str(e).startswith("That model is currently overloaded with other requests."):
                            retry = True
                            attempt += 1
            else:
                raise
```

**Comment by bigbabybubble** [comment]
for max attempt:

`        while answer is None:
            retry = True
            attempt = 0
            while retry:
                if attempt < 10:
                    try:
					
                        /code/

                    
                    except Exception as e:
                        if str(e).startswith("That model is currently overloaded with other requests."):
                            retry = True
                            attempt += 1
                else:
                    retry = False
                    raise Exception("max_attempt")`

**Comment by bigbabybubble** [comment]
for max attempt

`        while answer is None:
            retry = True
            attempt = 0
            while retry:
                if attempt < 10:
                    try:	
                        /code/
                    except Exception as e:
                        if str(e).startswith("That model is currently overloaded with other requests."):
                            retry = True
                            attempt += 1
                else:
                    retry = False
                    raise Exception("max_attempt")`

**Pull request closed without merging**
