### PR TITLE
Add commands suggestions via set_my_commands api method

### PR DESCRIPTION
**Pull request by gordinmitya**
It's more convenient to have autosuggestion and menu button in bot UI:

image

### CODE REVIEW

**Comment by karfly** [comment]
@gordinmitya 
Wow! Didn't know about this feature...

Can you please also delete section `Configure command hints (optional, but fancy)` from README.md to keep everything in one PR?

**Comment by karfly** [comment]
@EasonC13
It can be interesting for you

**Comment by EasonC13** [comment]
We can not change the comment hints. To set these shortcuts or preview prompts of the command, the bot owner should set it at BotFather.

Nevertheless, we may set it by [ReplyKeyboardMarkup](https://docs.python-telegram-bot.org/en/stable/telegram.replykeyboardmarkup.html) like the following image, so users can click these buttons to perform commands.
 
image



@gordinmitya  Is this what you want?

**Comment by karfly** [comment]
Nice job, thank you @gordinmitya ❤️ 
LET'S MERGE IT

**Pull request merged**
